sudo: required
services:
  - docker

before_install:
  - docker build -t gaurav2730/multi-docker-react-test -f ./client/Dockerfile.dev ./client 

script: #All tests come here
  - docker run gaurav2730/multi-docker-react-test npm test -- --coverage

after_success:
  - docker build -t gaurav2730/multi-container-client ./client 
  - docker build -t gaurav2730/multi-container-nginx ./nginx
  - docker build -t gaurav2730/multi-container-server ./server
  - docker build -t gaurav2730/multi-container-worker ./worker

  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  #Take the images and push them to docker hub
  - docker push gaurav2730/multi-container-client
  - docker push gaurav2730/multi-container-nginx
  - docker push gaurav2730/multi-container-server
  - docker push gaurav2730/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container-docker
  env: MultiContainerDocker-env
  bucket_name: elasticbeanstalk-us-east-2-881223701779
  bucket_path: multi-container-docker
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY 
